/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.genises.view;

import br.com.genises.model.Version;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Tiago
 */
public class GUIAbertura extends javax.swing.JFrame {

    /**
     * Creates new form GUIAbertura
     */
    Timer timer2;
    Timer timer1;
    
    public GUIAbertura(Version v) {
        
        initComponents();
        tfData.setText(v.getDataLancamento());
        txVersao.setText(v.getVersaoAtual());
        URL url = this.getClass().getResource("/br/com/genises/util/imagens/icon.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        timer1 = new Timer(1200, suaActionListenerImagem);
        timer1.start();
        lista.add("-");
        lista.add("--");
        lista.add("---");
        lista.add("-----");
        lista.add("------");
        lista.add("----------");
        lista.add("-------------");
        lista.add("-------------------");
        lista.add("------------------------");
        lista.add("----------------------------");
        lista.add("------------------------------------");
        lista.add("Atualizando Base");
        lista.add("Verificando Licença");
        
    }
    List<String> lista = new ArrayList<>();
    GUILogin guiLogin = new GUILogin(this);
    int a = 0;
    ActionListener suaActionListenerImagem = new ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent e) {
            if (lista.size() <= a) {
                timer1.stop();
                try {
                    
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
                Dimension paneSize = guiLogin.getSize();
                Dimension screenSize = guiLogin.getToolkit().getScreenSize();
                guiLogin.setLocation((screenSize.width - paneSize.width) / 2, (screenSize.height - paneSize.height) / 2);
                guiLogin.setVisible(true);
                fechar();
                
            } else {
                tfMensagem.setText(lista.get(a));
                a++;
            }
            
        }
        
    };
    
    public void fechar() {
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        txVersao = new javax.swing.JLabel();
        tfMensagem = new javax.swing.JLabel();
        tfData = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setType(java.awt.Window.Type.POPUP);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        txVersao.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txVersao.setForeground(new java.awt.Color(255, 255, 255));
        txVersao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        tfMensagem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfMensagem.setForeground(new java.awt.Color(255, 255, 255));
        tfMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        tfData.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tfData.setForeground(new java.awt.Color(255, 255, 255));
        tfData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/genises/util/imagens/TELA DE ABERTURA.jpg"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        menu.setBackground(new java.awt.Color(0, 51, 51));
        menu.setForeground(new java.awt.Color(0, 51, 51));
        menu.setAlignmentX(0.0F);
        menu.setMaximumSize(new java.awt.Dimension(0, 0));
        menu.setMinimumSize(new java.awt.Dimension(0, 0));
        menu.setPreferredSize(new java.awt.Dimension(0, 0));

        jMenu1.setText(".");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_0, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        menu.add(jMenu1);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1)
            .addGroup(layout.createSequentialGroup()
                .addGap(510, 510, 510)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txVersao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfData, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(tfMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(txVersao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(tfData, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        

    }//GEN-LAST:event_formKeyPressed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuBar menu;
    private javax.swing.JLabel tfData;
    private javax.swing.JLabel tfMensagem;
    private javax.swing.JLabel txVersao;
    // End of variables declaration//GEN-END:variables
}
