/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.genises.view.internal;

import br.com.genises.model.Banco;
import br.com.genises.negocio.BBanco;
import br.com.genises.util.validacoes.UpperCaseDocument;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class GUIAlteraBanco extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUICadastroBanco
     */
    JInternalFrame principal;
    Banco bancoR = new Banco();
    
    public GUIAlteraBanco(Banco banco, JInternalFrame frame) {
        initComponents();
        principal = frame;
        upperCase();
        bancoR = banco;
        preencheCampos(banco);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfBanco = new javax.swing.JTextField();
        tfAgencia = new javax.swing.JTextField();
        tfConta = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tfTitular = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfGerente = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Sistema Gênises - Cadastro de Bancos");

        jLabel1.setText("Banco:");

        jLabel2.setText("Agência:");

        jLabel3.setText("Conta:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/genises/util/imagens/gravar_vectorized.png"))); // NOI18N
        jButton1.setText("Gravar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/genises/util/imagens/limpar_vectorized_1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/genises/util/imagens/fechar_vectorized.png"))); // NOI18N
        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Titular:");

        jLabel5.setText("Gerente:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfBanco)
                    .addComponent(tfTitular)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfAgencia)
                                .addComponent(tfConta, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3)))
                        .addGap(0, 66, Short.MAX_VALUE))
                    .addComponent(tfGerente))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton3)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            verificaCampos();
            
            verificaExistencia();
            gravar();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        limparCampos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tfAgencia;
    private javax.swing.JTextField tfBanco;
    private javax.swing.JTextField tfConta;
    private javax.swing.JTextField tfGerente;
    private javax.swing.JTextField tfTitular;
    // End of variables declaration//GEN-END:variables

    private void verificaCampos() throws Exception {
        if (tfBanco.getText().trim().equals("")) {
            throw new Exception("INFORME O NOME DO BANCO!");
        }
        if (tfAgencia.getText().trim().equals("")) {
            throw new Exception("DIGITE O NUMERO DA AGENCIA!");
        }
        if (tfConta.getText().trim().equals("")) {
            throw new Exception("DIGITE O NUMERO DA CONTA!");
        }
        if (tfTitular.getText().trim().equals("")) {
            throw new Exception("DIGITE O NUMERO DO TITULAR DA CONTA!");
        }
        if (tfGerente.getText().trim().equals("")) {
            throw new Exception("DIGITE O NOME DO GERENTE!");
        }
    }
    
    private void verificaExistencia() throws Exception {
        BBanco bBanco = new BBanco();
        Banco bancoV = new Banco();
        bancoV.setBanco(tfBanco.getText());
        bancoV.setAgencia(tfAgencia.getText());
        bancoV.setConta(tfConta.getText());
        
        if (bancoR.getAgencia().equals(tfAgencia.getText())) {
            //faz nada
        } else if (bBanco.verificaExistencia(bancoV) == true) {
            throw new Exception("A CONTA INFORMADA JÁ EXISTE");
        }
        
        if (bancoR.getConta().equals(tfConta.getText())) {
            // faz nada
        } else if (bBanco.verificaExistencia(bancoV) == true) {
            throw new Exception("A CONTA INFORMADA JÁ EXISTE");
        }
        
    }
    
    private void gravar() throws Exception {
        BBanco bBanco = new BBanco();
        Banco b = new Banco();
        b.setId(bancoR.getId());
        b.setBanco(tfBanco.getText());
        b.setAgencia(tfAgencia.getText());
        b.setConta(tfConta.getText());
        b.setTitular(tfTitular.getText());
        b.setGerente(tfGerente.getText());
        bBanco.update(b);
        tfBanco.requestFocus();
        JOptionPane.showMessageDialog(this, "Alteração realizada com sucesso!");
        limparCampos();
    }
    
    private void upperCase() {
        tfBanco.setDocument(new UpperCaseDocument());
        tfTitular.setDocument(new UpperCaseDocument());
        tfGerente.setDocument(new UpperCaseDocument());
    }
    
    private void limparCampos() {
        tfBanco.setText(null);
        tfAgencia.setText(null);
        tfConta.setText(null);
        tfTitular.setText(null);
        tfGerente.setText(null);
        
    }
    
    private void preencheCampos(Banco banco) {
        tfBanco.setText(banco.getBanco());
        tfAgencia.setText(banco.getAgencia());
        tfConta.setText(banco.getConta());
        tfTitular.setText(banco.getTitular());
        tfGerente.setText(banco.getGerente());
        
    }
}
