/*
 * Here comes the text of your license
 * Each line should be prefixed with  * 
 */
package br.com.genises.view.internal;

import br.com.genises.dao.DaoMembro;
import br.com.genises.model.Celula;
import br.com.genises.model.Cidade;
import br.com.genises.model.Membro;
import br.com.genises.negocio.BCidade;
import br.com.genises.negocio.BMembro;
import br.com.genises.util.validacoes.ValidaCPF;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;

/**
 *
 * @author rober
 */
public class GUICadastroMembrasia extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUICadastroMembrasia
     */
    public GUICadastroMembrasia() {
        initComponents();
        tfCpf.setFocusLostBehavior(JFormattedTextField.COMMIT);
        formatacao();
        formatarDatas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gOutraIgreja = new javax.swing.ButtonGroup();
        gLiderCelula = new javax.swing.ButtonGroup();
        gAnfitriaoCelula = new javax.swing.ButtonGroup();
        gPercenteCelula = new javax.swing.ButtonGroup();
        gDiscipulado = new javax.swing.ButtonGroup();
        gLiderTreinamento = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        tfEndereco = new javax.swing.JTextField();
        tfBairro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfCEP = new javax.swing.JTextField();
        cbUF = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        cbCidade = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfRg = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfOrgao = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cbUfOrgao = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tfPai = new javax.swing.JTextField();
        tfMae = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tfNaturalDe = new javax.swing.JTextField();
        tfTelefone = new javax.swing.JFormattedTextField();
        tfCelular = new javax.swing.JFormattedTextField();
        tfCpf = new javax.swing.JFormattedTextField();
        cbEstadoCivil = new javax.swing.JComboBox();
        tfDataNascimento = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tfMinistro = new javax.swing.JTextField();
        jOutraSim = new javax.swing.JRadioButton();
        jOutraNao = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        tfIgrejaOrigem = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        tfCargo1 = new javax.swing.JTextField();
        tfCargo2 = new javax.swing.JTextField();
        tfCargo3 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLiderSim = new javax.swing.JRadioButton();
        jLiderNao = new javax.swing.JRadioButton();
        jAnfitriaoSim = new javax.swing.JRadioButton();
        jAnfitriaoNao = new javax.swing.JRadioButton();
        jPercenteSim = new javax.swing.JRadioButton();
        jPertenceNao = new javax.swing.JRadioButton();
        jDiscipuladoSim = new javax.swing.JRadioButton();
        jDiscipuladoNao = new javax.swing.JRadioButton();
        jLabel34 = new javax.swing.JLabel();
        jLiderTreinamentoSim = new javax.swing.JRadioButton();
        jLiderTreinamentoNao = new javax.swing.JRadioButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        tfAnfitriaoOnde = new javax.swing.JTextField();
        tfDiscipulador = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfObs = new javax.swing.JTextArea();
        tfDataBatismo = new javax.swing.JFormattedTextField();

        setClosable(true);
        setTitle("Sistema Gênises - Cadastro de Membrasia");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Pessoais"));

        jLabel1.setText("Nome:");

        jLabel2.setText("Endereço:");

        jLabel3.setText("Bairro:");

        jLabel4.setText("UF:");

        jLabel5.setText("Telefone:");

        jLabel6.setText("Email:");

        jLabel7.setText("CPF:");

        tfNome.setText("ROBERT");

        tfEndereco.setText("RUA 45");

        tfBairro.setText("VERA CRUZ");

        jLabel8.setText("CEP:");

        tfCEP.setText("76380000");

        cbUF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));
        cbUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUFActionPerformed(evt);
            }
        });

        jLabel9.setText("Cidade:");

        cbCidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione..." }));

        jLabel10.setText("Celular:");

        tfEmail.setText("ROBERT@GMAIL.COM");

        jLabel11.setText("RG:");

        tfRg.setText("78125");

        jLabel12.setText("Orgão Emissor:");

        tfOrgao.setText("SPTC");

        jLabel13.setText("UF RG:");

        cbUfOrgao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Filiação"));

        jLabel14.setText("Pai:");

        jLabel15.setText("Mãe:");

        tfPai.setText("CLAUDIO");

        tfMae.setText("LUCIMAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfPai, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(tfMae)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tfPai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tfMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel16.setText("Data Nascimento:");

        jLabel17.setText("Estado Civil:");

        jLabel19.setText("Natural de:");

        tfNaturalDe.setText("GOIANESIA");

        try {
            tfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(0xx##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfTelefone.setText("(0xx62)8438-0136");

        try {
            tfCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(0xx##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfCelular.setText("(0xx62)8438-0136");

        try {
            tfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCpfFocusLost(evt);
            }
        });

        cbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "SOLTEIRO", "CASADO", "DIVORCIÁDO", "VIÚVO" }));

        tfDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel4)
                                .addGap(4, 4, 4)
                                .addComponent(cbUF, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(41, 41, 41)
                                    .addComponent(jLabel8)
                                    .addGap(4, 4, 4)
                                    .addComponent(tfCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel17)
                                    .addGap(10, 10, 10)
                                    .addComponent(cbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel19)
                                        .addGap(4, 4, 4)
                                        .addComponent(tfNaturalDe, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(20, 20, 20)
                                            .addComponent(jLabel5)
                                            .addGap(4, 4, 4)
                                            .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(4, 4, 4)
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel7)
                                                        .addGap(4, 4, 4)
                                                        .addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(10, 10, 10)
                                                        .addComponent(jLabel11)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(tfRg, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel13)
                                                        .addGap(4, 4, 4)
                                                        .addComponent(cbUfOrgao, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(10, 10, 10)
                                                        .addComponent(jLabel12)
                                                        .addGap(4, 4, 4)
                                                        .addComponent(tfOrgao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8))
                    .addComponent(tfCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel17))
                    .addComponent(cbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNaturalDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel16))))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10))))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbUfOrgao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfOrgao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))))
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/genises/util/imagens/salvar icone_vectorized.png"))); // NOI18N
        jButton1.setText("Gravar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/genises/util/imagens/limpar_vectorized_1.png"))); // NOI18N

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/genises/util/imagens/fechar_vectorized_1.png"))); // NOI18N
        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Outras Informações"));

        jLabel22.setText("Batismo nas Águas:");

        jLabel23.setText("Veio de Outra Igreja Evangelica:");

        jLabel24.setText("Ministro:");

        gOutraIgreja.add(jOutraSim);
        jOutraSim.setText("Sim");
        jOutraSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOutraSimActionPerformed(evt);
            }
        });

        gOutraIgreja.add(jOutraNao);
        jOutraNao.setText("Não");
        jOutraNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOutraNaoActionPerformed(evt);
            }
        });

        jLabel25.setText("Qual:");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Cargo que Ocupa"));

        jLabel26.setText("1:");

        jLabel27.setText("2:");

        jLabel28.setText("3:");

        tfCargo1.setText("NENHUM");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCargo1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCargo3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCargo2)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(tfCargo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(tfCargo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(tfCargo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel29.setText("Lider de Celula:");

        jLabel30.setText("Anfitrião de Celula:");

        jLabel31.setText("Pertence a uma Celula:");

        jLabel32.setText("Esta no Discipulado:");

        jLabel33.setText("Obs:");

        gLiderCelula.add(jLiderSim);
        jLiderSim.setText("Sim");

        gLiderCelula.add(jLiderNao);
        jLiderNao.setText("Não");

        gAnfitriaoCelula.add(jAnfitriaoSim);
        jAnfitriaoSim.setText("Sim");
        jAnfitriaoSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAnfitriaoSimActionPerformed(evt);
            }
        });

        gAnfitriaoCelula.add(jAnfitriaoNao);
        jAnfitriaoNao.setText("Não");
        jAnfitriaoNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAnfitriaoNaoActionPerformed(evt);
            }
        });

        gPercenteCelula.add(jPercenteSim);
        jPercenteSim.setText("Sim");
        jPercenteSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPercenteSimActionPerformed(evt);
            }
        });

        gPercenteCelula.add(jPertenceNao);
        jPertenceNao.setText("Não");
        jPertenceNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPertenceNaoActionPerformed(evt);
            }
        });

        gDiscipulado.add(jDiscipuladoSim);
        jDiscipuladoSim.setText("Sim");
        jDiscipuladoSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDiscipuladoSimActionPerformed(evt);
            }
        });

        gDiscipulado.add(jDiscipuladoNao);
        jDiscipuladoNao.setText("Não");
        jDiscipuladoNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDiscipuladoNaoActionPerformed(evt);
            }
        });

        jLabel34.setText("Lider em Treinamento:");

        gLiderTreinamento.add(jLiderTreinamentoSim);
        jLiderTreinamentoSim.setText("Sim");

        gLiderTreinamento.add(jLiderTreinamentoNao);
        jLiderTreinamentoNao.setText("Não");

        jLabel35.setText("Onde:");

        jLabel37.setText("Discipulador:");

        tfObs.setColumns(20);
        tfObs.setRows(5);
        jScrollPane1.setViewportView(tfObs);

        tfDataBatismo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel22)
                .addGap(16, 16, 16)
                .addComponent(tfDataBatismo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel23)
                .addGap(6, 6, 6)
                .addComponent(jOutraSim)
                .addGap(2, 2, 2)
                .addComponent(jOutraNao)
                .addGap(0, 0, 0)
                .addComponent(jLabel25)
                .addGap(4, 4, 4)
                .addComponent(tfIgrejaOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel24)
                .addGap(4, 4, 4)
                .addComponent(tfMinistro, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel29))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel30))
                    .addComponent(jLabel31))
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLiderSim)
                    .addComponent(jAnfitriaoSim)
                    .addComponent(jPercenteSim)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLiderNao)
                            .addComponent(jPertenceNao)
                            .addComponent(jAnfitriaoNao))))
                .addGap(36, 36, 36)
                .addComponent(jLabel35)
                .addGap(4, 4, 4)
                .addComponent(tfAnfitriaoOnde, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel32))
                    .addComponent(jLabel34))
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDiscipuladoSim)
                    .addComponent(jLiderTreinamentoSim, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLiderTreinamentoNao)
                            .addComponent(jDiscipuladoNao))))
                .addGap(5, 5, 5)
                .addComponent(jLabel37)
                .addGap(4, 4, 4)
                .addComponent(tfDiscipulador, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel33)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel22))
                    .addComponent(tfDataBatismo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel23))
                    .addComponent(jOutraSim)
                    .addComponent(jOutraNao)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel25))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(tfIgrejaOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(tfMinistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel30)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel31))
                    .addComponent(jLiderNao)
                    .addComponent(jLiderSim)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jAnfitriaoSim))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPercenteSim))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPertenceNao))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jAnfitriaoNao))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel35))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(tfAnfitriaoOnde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel32)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel34))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDiscipuladoSim)
                            .addComponent(jDiscipuladoNao)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLiderTreinamentoNao)
                                    .addComponent(jLiderTreinamentoSim)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel37))
                    .addComponent(tfDiscipulador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            verificarCampos();
            gravar();
            limparCampos();
            formatacao();

// TODO add your handling code here:
        } catch (ParseException ex) {
            Logger.getLogger(GUICadastroMembrasia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jOutraNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOutraNaoActionPerformed
        tfIgrejaOrigem.setText(null);
        tfIgrejaOrigem.setEnabled(false);
    }//GEN-LAST:event_jOutraNaoActionPerformed

    private void jOutraSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOutraSimActionPerformed
        tfIgrejaOrigem.setEnabled(true);
    }//GEN-LAST:event_jOutraSimActionPerformed

    private void jAnfitriaoNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAnfitriaoNaoActionPerformed
        tfAnfitriaoOnde.setText(null);
        tfAnfitriaoOnde.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jAnfitriaoNaoActionPerformed

    private void jAnfitriaoSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAnfitriaoSimActionPerformed
        tfAnfitriaoOnde.setEnabled(true);
    }//GEN-LAST:event_jAnfitriaoSimActionPerformed

    private void jPercenteSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPercenteSimActionPerformed
//        cbCelula.setEnabled(true);
    }//GEN-LAST:event_jPercenteSimActionPerformed

    private void jPertenceNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPertenceNaoActionPerformed
//        cbCelula.setSelectedIndex(0);
//        cbCelula.setEnabled(false);
    }//GEN-LAST:event_jPertenceNaoActionPerformed

    private void jDiscipuladoNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDiscipuladoNaoActionPerformed
        tfDiscipulador.setText(null);
        tfDiscipulador.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jDiscipuladoNaoActionPerformed

    private void jDiscipuladoSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDiscipuladoSimActionPerformed
        tfDiscipulador.setEnabled(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jDiscipuladoSimActionPerformed

    private void tfCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCpfFocusLost
        try {
            verificaCpf();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }//GEN-LAST:event_tfCpfFocusLost

    private void cbUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUFActionPerformed
        try {
            if (cbUF.getSelectedItem().equals("Selecione...")) {

            } else {
                BCidade bCidade = new BCidade();
                List<Cidade> cidades = new ArrayList<>();
                String uf = (String) cbUF.getSelectedItem();
                cidades = bCidade.buscaCidade(uf);
                cbCidade.setEnabled(true);
                carregarCidades(cidades);
                cbCidade.requestFocus();
            }
        } catch (Exception ex) {

        }        // TODO add your handling code here:
    }//GEN-LAST:event_cbUFActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
    private void carregarCidades(List<Cidade> cidades) {
        cbCidade.removeAllItems();
        cbCidade.addItem("Selecione...");
        try {
            for (int i = 0; i < cidades.size(); i++) {

                cbCidade.addItem(cidades.get(i).getCidade());
                cbCidade.setSelectedIndex(0);
            }
        } catch (Exception ex) {
            Logger.getLogger(GUICadastroIgreja.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbCidade;
    private javax.swing.JComboBox cbEstadoCivil;
    private javax.swing.JComboBox cbUF;
    private javax.swing.JComboBox cbUfOrgao;
    private javax.swing.ButtonGroup gAnfitriaoCelula;
    private javax.swing.ButtonGroup gDiscipulado;
    private javax.swing.ButtonGroup gLiderCelula;
    private javax.swing.ButtonGroup gLiderTreinamento;
    private javax.swing.ButtonGroup gOutraIgreja;
    private javax.swing.ButtonGroup gPercenteCelula;
    private javax.swing.JRadioButton jAnfitriaoNao;
    private javax.swing.JRadioButton jAnfitriaoSim;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JRadioButton jDiscipuladoNao;
    private javax.swing.JRadioButton jDiscipuladoSim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jLiderNao;
    private javax.swing.JRadioButton jLiderSim;
    private javax.swing.JRadioButton jLiderTreinamentoNao;
    private javax.swing.JRadioButton jLiderTreinamentoSim;
    private javax.swing.JRadioButton jOutraNao;
    private javax.swing.JRadioButton jOutraSim;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jPercenteSim;
    private javax.swing.JRadioButton jPertenceNao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfAnfitriaoOnde;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JTextField tfCEP;
    private javax.swing.JTextField tfCargo1;
    private javax.swing.JTextField tfCargo2;
    private javax.swing.JTextField tfCargo3;
    private javax.swing.JFormattedTextField tfCelular;
    private javax.swing.JFormattedTextField tfCpf;
    private javax.swing.JFormattedTextField tfDataBatismo;
    private javax.swing.JFormattedTextField tfDataNascimento;
    private javax.swing.JTextField tfDiscipulador;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfIgrejaOrigem;
    private javax.swing.JTextField tfMae;
    private javax.swing.JTextField tfMinistro;
    private javax.swing.JTextField tfNaturalDe;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextArea tfObs;
    private javax.swing.JTextField tfOrgao;
    private javax.swing.JTextField tfPai;
    private javax.swing.JTextField tfRg;
    private javax.swing.JFormattedTextField tfTelefone;
    // End of variables declaration//GEN-END:variables

    private void gravar() throws ParseException, Exception {
        Membro m = new Membro();
        BMembro bMembro = new BMembro();
        Cidade c = new Cidade();
        Celula celula = new Celula();

        m.setNome(tfNome.getText());
        m.setEndereco(tfEndereco.getText());
        m.setBairro(tfBairro.getText());
        m.setCep(tfCEP.getText());
        c.setUf((String) cbUF.getSelectedItem());
        c.setCidade((String) cbCidade.getSelectedItem());
        m.setCidade(c);
        m.setTelefone(tfTelefone.getText());
        m.setCelular(tfCelular.getText());
        m.setEmail(tfEmail.getText());
        m.setCpf(tfCpf.getText());
        m.setRg(tfRg.getText());
        m.setOrgaoEmissor(tfOrgao.getText());
        m.setUfOrgao((String) cbUfOrgao.getSelectedItem());
        m.setPai(tfPai.getText());
        m.setMae(tfMae.getText());

        String dataNascimento = tfDataNascimento.getText();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        java.util.Date dataNascimentoForm = formato.parse(dataNascimento);
        m.setNascimento(dataNascimentoForm);

        m.setNaturalDe(tfNaturalDe.getText());
        m.setEstadoCivil((String) cbEstadoCivil.getSelectedItem());

        String dataBatismo = tfDataNascimento.getText();
        java.util.Date dataBatismoForm = formato.parse(dataBatismo);
        m.setBatismoAgua(dataBatismoForm);

        m.setNomeMinistro(tfMinistro.getText());

        if (jOutraNao.isSelected()) {
            m.setOutraIgreja(false);
        } else {
            m.setOutraIgreja(true);
        }

        m.setNomeIgreja(tfIgrejaOrigem.getText());
        m.setCargo1(tfCargo1.getText());
        m.setCargo2(tfCargo2.getText());
        m.setCargo3(tfCargo3.getText());

        if (jLiderNao.isSelected()) {
            m.setLiderCelula(false);
        } else {
            m.setLiderCelula(true);
        }

        if (jLiderTreinamentoNao.isSelected()) {
            m.setLidertreinamento(false);
        } else {
            m.setLidertreinamento(true);
        }

        if (jAnfitriaoNao.isSelected()) {
            m.setAnfitriao(false);
        } else {
            m.setAnfitriao(true);
        }

        m.setAnfitriaoOnde(tfAnfitriaoOnde.getText());

        if (jPertenceNao.isSelected()) {
            m.setCelula(false);
        } else {
            m.setCelula(true);
        }

//        celula.setNome((String) cbCelula.getSelectedItem());
//        m.setNomeCelula(celula);
        if (jDiscipuladoNao.isSelected()) {
            m.setDiscipulado(false);
        } else {
            m.setDiscipulado(true);
        }
        m.setNomeDiscipulador(tfDiscipulador.getText());
        m.setObs(tfObs.getText());

        bMembro.gravar(m);
        JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso!");

    }

    private void formatacao() {
        jOutraNao.setSelected(true);
        tfIgrejaOrigem.setEnabled(false);
        jLiderNao.setSelected(true);
        jLiderTreinamentoNao.setSelected(true);
        jAnfitriaoNao.setSelected(true);
        tfAnfitriaoOnde.setEnabled(false);
        jPertenceNao.setSelected(true);
//        cbCelula.setEnabled(false);
        jDiscipuladoNao.setSelected(true);
        tfDiscipulador.setEnabled(false);

    }

    private void verificaCpf() throws Exception {
        if (tfCpf.getText().trim().length() == 14) {

            if (ValidaCPF.isCPF(tfCpf.getText().replace("-", "").replace(".", "")) == false) {
                tfCpf.requestFocus();
                throw new Exception("O CPF informado não é válido!");
            } else {
                BMembro bMembro = new BMembro();
                if (bMembro.verificaExistencia(tfCpf.getText().replace("-", "").replace(".", "")) == true) {
                    tfCpf.setText(null);
                    tfCpf.requestFocus();
                    throw new Exception("O CPF informado já está cadastrado");
                }
            }
        }
    }

    private void limparCampos() {
        tfDataNascimento.setText(null);
        tfDataBatismo.setText(null);
        tfTelefone.setText(null);
        tfCelular.setText(null);
        cbUF.setSelectedIndex(0);
        cbCidade.setSelectedIndex(0);
        cbUfOrgao.setSelectedIndex(0);
//        cbCelula.setSelectedIndex(0);
        tfCpf.setText(null);
        initComponents();

    }

    private void verificarCampos() throws Exception {
        if (tfCpf.getText().equals("   .   .   -  ")) {
            tfCpf.requestFocus();
            throw new Exception("DIGITE O CPF!");
        }
        if (tfNome.getText().trim().equals("")) {
            tfNome.requestFocus();
            throw new Exception("DIGITE O NOME!");
        }
        if (tfEndereco.getText().trim().equals("")) {
            tfNome.requestFocus();
            throw new Exception("DIGITE O ENDEREÇO!");
        }
        if (tfBairro.getText().trim().equals("")) {
            tfNome.requestFocus();
            throw new Exception("DIGITE O BAIRRO!");
        }
        if (tfCEP.getText().trim().equals("")) {
            tfNome.requestFocus();
            throw new Exception("DIGITE O CEP!");
        }
        if (tfEmail.getText().trim().equals("")) {
            tfNome.requestFocus();
            throw new Exception("DIGITE O EMAIL!");
        }
        if (tfRg.getText().trim().equals("")) {
            tfNome.requestFocus();
            throw new Exception("DIGITE O RG!");
        }
        if (cbUfOrgao.getSelectedIndex() == 0) {
            tfNome.requestFocus();
            throw new Exception("SELECIONE O ESTADO DA RG!");
        }
        if (tfOrgao.getText().trim().equals("")) {
            tfNome.requestFocus();
            throw new Exception("DIGITE O ORGÃO EMISSOR!");
        }
        if (tfPai.getText().trim().equals("")) {
            tfNome.requestFocus();
            throw new Exception("DIGITE O NOME DO PAI!");
        }
        if (tfMae.getText().trim().equals("")) {
            tfNome.requestFocus();
            throw new Exception("DIGITE O NOME DA MÃE!");
        }
        if (tfNaturalDe.getText().trim().equals("")) {
            tfNome.requestFocus();
            throw new Exception("DIGITE O NOME DA CIDADE DE NASCIMENTO!");
        }
        if (cbEstadoCivil.getSelectedIndex() == 0) {
            tfNome.requestFocus();
            throw new Exception("SELECIONE UM ESTADO DE NASCIMENTO!");
        }
        if (cbUF.getSelectedIndex() == 0) {
            tfNome.requestFocus();
            throw new Exception("SELECIONE UM ESTADO!");
        }
        if (cbCidade.getSelectedIndex() == 0) {
            tfNome.requestFocus();
            throw new Exception("SELECIONE UMA CIDADE!");
        }
        if (jOutraSim.isSelected()) {
            if (tfIgrejaOrigem.getText().equals("")) {
                tfIgrejaOrigem.requestFocus();
                throw new Exception("INFORME O NOME DA IGREJA DE ORIGEM!");
            }
            if (jAnfitriaoSim.isSelected()) {
                if (tfAnfitriaoOnde.getText().equals("")) {
                    tfAnfitriaoOnde.requestFocus();
                    throw new Exception("INFORME DE ONDE É ANFITRIÃO!");
                }
            }
            if (jDiscipuladoSim.isSelected()) {
                if (tfDiscipulador.getText().equals("")) {
                    tfDiscipulador.requestFocus();
                    throw new Exception("INFORME O NOME DO DISCIPULADOR!");
                }
            }
        }
    }

    private void formatarDatas() {
        Date dataAtualMin = new Date(System.currentTimeMillis());

    }
}
