/*
 * Here comes the text of your license
 * Each line should be prefixed with  * 
 */
package br.com.genises.view.internal;

import br.com.genises.model.Cidade;
import br.com.genises.model.ResponsavelLegal;
import br.com.genises.negocio.BCidade;
import br.com.genises.negocio.BContador;
import br.com.genises.negocio.BResponsavel;
import br.com.genises.util.validacoes.UpperCaseDocument;
import br.com.genises.util.validacoes.ValidaData;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;

/**
 *
 * @author rober
 */
public class GUICadastroResponsavel extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUICadastroResponsavel
     */
    ResponsavelLegal responsavelRecebido = new ResponsavelLegal();

    public GUICadastroResponsavel(ResponsavelLegal responsavel) {
        initComponents();

        tfCpf.setFocusLostBehavior(JFormattedTextField.COMMIT);
        tfDataEmissaoRg.setFocusLostBehavior(JFormattedTextField.COMMIT);

        upperCase();
        responsavelRecebido = responsavel;
        verificaExistencia(responsavelRecebido);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        tfEndereco = new javax.swing.JTextField();
        tfBairro = new javax.swing.JTextField();
        cbUf = new javax.swing.JComboBox();
        tfEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfCep = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbCidade = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfRg = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cbUfRg = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        tfOrgaoEmissor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        tfCpf = new javax.swing.JFormattedTextField();
        tfDataEmissaoRg = new javax.swing.JFormattedTextField();
        tfCelular = new javax.swing.JFormattedTextField();
        tfTelefone = new javax.swing.JFormattedTextField();

        setClosable(true);
        setTitle("Sistema Gênises - Cadastro Responsável Legal");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Responsável Legal"));

        jLabel1.setText("Nome:");

        jLabel2.setText("Endereço:");

        jLabel3.setText("Bairro:");

        jLabel4.setText("UF:");

        jLabel5.setText("Telefone:");

        jLabel6.setText("Email:");

        jLabel7.setText("CPF:");

        jLabel8.setText("Data da Emissão:");

        cbUf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));
        cbUf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUfActionPerformed(evt);
            }
        });

        jLabel9.setText("CEP:");

        jLabel10.setText("Cidade:");

        cbCidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione..." }));

        jLabel11.setText("Celular:");

        jLabel12.setText("RG:");

        jLabel13.setText("UF RG:");

        cbUfRg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));

        jLabel14.setText("Orgão Emissor:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/genises/util/imagens/salvar icone_vectorized.png"))); // NOI18N
        jButton1.setText("Gravar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/genises/util/imagens/fechar_vectorized_1.png"))); // NOI18N
        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        try {
            tfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            tfDataEmissaoRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfDataEmissaoRg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDataEmissaoRgFocusLost(evt);
            }
        });

        try {
            tfCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(0xx##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            tfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(0xx##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNome)
                    .addComponent(tfEndereco)
                    .addComponent(tfEmail)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCep))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbUf, 0, 151, Short.MAX_VALUE)
                            .addComponent(tfTelefone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbCidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCelular))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(tfDataEmissaoRg, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfRg, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbUfRg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfOrgaoEmissor))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jButton1)
                        .addGap(8, 8, 8)
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(tfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12)
                    .addComponent(tfRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(cbUfRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel14)
                    .addComponent(tfOrgaoEmissor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDataEmissaoRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbUfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUfActionPerformed

        try {
            if (cbUf.getSelectedItem().equals("Selecione...")) {

            } else {
                BCidade bCidade = new BCidade();
                List<Cidade> cidades = new ArrayList<>();
                String uf = (String) cbUf.getSelectedItem();
                cidades = bCidade.buscaCidade(uf);
                cbCidade.setEnabled(true);
                carregarCidades(cidades);
                cbCidade.requestFocus();
            }
        } catch (Exception ex) {

        }        // TODO add your handling code here:
    }//GEN-LAST:event_cbUfActionPerformed
    private void carregarCidades(List<Cidade> cidades) {
        cbCidade.removeAllItems();
        cbCidade.addItem("Selecione...");
        try {
            for (int i = 0; i < cidades.size(); i++) {

                cbCidade.addItem(cidades.get(i).getCidade());
                cbCidade.setSelectedIndex(0);
            }
        } catch (Exception ex) {
            Logger.getLogger(GUICadastroIgreja.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            validarCampos();
            validarData();
            gravar();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfDataEmissaoRgFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDataEmissaoRgFocusLost
        
        if (ValidaData.isValidDate(tfDataEmissaoRg.getText()) == false || ValidaData.dataMaiorSistema(tfDataEmissaoRg.getText()) == true) {
            JOptionPane.showMessageDialog(null, "A DATA INFORMADA NÃO É VÁLIDA!");
            tfDataEmissaoRg.requestFocus();
        } else {

        }        // TODO add your handling code here:
    }//GEN-LAST:event_tfDataEmissaoRgFocusLost

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbCidade;
    private javax.swing.JComboBox cbUf;
    private javax.swing.JComboBox cbUfRg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JFormattedTextField tfCelular;
    private javax.swing.JTextField tfCep;
    private javax.swing.JFormattedTextField tfCpf;
    private javax.swing.JFormattedTextField tfDataEmissaoRg;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfOrgaoEmissor;
    private javax.swing.JTextField tfRg;
    private javax.swing.JFormattedTextField tfTelefone;
    // End of variables declaration//GEN-END:variables

    private void upperCase() {
        tfNome.setDocument(new UpperCaseDocument());
        tfBairro.setDocument(new UpperCaseDocument());
        tfEndereco.setDocument(new UpperCaseDocument());
        tfEmail.setDocument(new UpperCaseDocument());
        tfOrgaoEmissor.setDocument(new UpperCaseDocument());

    }

    private void verificaExistencia(ResponsavelLegal responsavelR) {

        if (responsavelR.getId() != 0) {
            carregarDados();

        } else {

        }

    }

    private void carregarDados() {
        tfNome.setText(responsavelRecebido.getNome());
        tfEndereco.setText(responsavelRecebido.getEndereco());
        tfBairro.setText(responsavelRecebido.getBairro());
        tfCep.setText(responsavelRecebido.getCep());
        cbUf.setSelectedItem(responsavelRecebido.getCidade().getUf());
        cbCidade.setSelectedItem(responsavelRecebido.getCidade().getCidade());
        tfTelefone.setText(responsavelRecebido.getTelefone());
        tfCelular.setText(responsavelRecebido.getCelular());
        tfEmail.setText(responsavelRecebido.getEmail());
        tfCpf.setText(responsavelRecebido.getCpf());

        SimpleDateFormat s = new SimpleDateFormat("dd/MM/yyyy");

        tfRg.setText(responsavelRecebido.getRg());
        tfOrgaoEmissor.setText(responsavelRecebido.getOrgaoEmissor());
        cbUfRg.setSelectedItem(responsavelRecebido.getUfRg());

        String dataEmissaoRG = s.format(responsavelRecebido.getEmissaoRg().getTime());
        tfDataEmissaoRg.setText(dataEmissaoRG);

    }

    private void validarCampos() throws Exception {

        if (tfNome.getText().trim().equals("")) {
            tfNome.requestFocus();
            throw new Exception("DIGITE O NOME!");

        }
        if (tfEndereco.getText().trim().equals("")) {
            tfEndereco.requestFocus();
            throw new Exception("DIGITE O ENDEREÇO!");
        }
        if (tfBairro.getText().trim().equals("")) {
            tfBairro.requestFocus();
            throw new Exception("DIGITE O BAIRRO!");
        }
        if (tfCep.getText().trim().equals("")) {
            tfCep.requestFocus();
            throw new Exception("DIGITE O CEP!");
        }
        if (cbUf.getSelectedItem().equals("Selecione...")) {
            cbUf.requestFocus();
            throw new Exception("SELECIONE UM ESTADO!");
        }
        if (cbCidade.getSelectedItem().equals("Selecione...")) {
            cbCidade.requestFocus();
            throw new Exception("SELECIONE UMA CIDADE!");
        }
        if (tfTelefone.getText().equals("(0xx  )    -    ")) {
            tfTelefone.requestFocus();
            throw new Exception("INFORME UM NUMERO DE TELEFONE!");
        }
        if (tfCelular.getText().equals("(0xx  )    -    ")) {
            tfCelular.requestFocus();
            throw new Exception("INFORME UM NUMERO DE CELULAR!");
        }
        if (tfEmail.getText().trim().equals("")) {
            tfEmail.requestFocus();
            throw new Exception("INFORME UM ENDEREÇO DE EMAIL!");
        }
        if (tfCpf.getText().trim().equals("")) {
            tfCpf.requestFocus();
            throw new Exception("INFORME UM CNPJ VÁLIDO!");
        }
        if (tfRg.getText().trim().equals("")) {
            tfRg.requestFocus();
            throw new Exception("INFORME UM RG VÁLIDO!");
        }
        if (tfOrgaoEmissor.getText().trim().equals("")) {
            tfOrgaoEmissor.requestFocus();
            throw new Exception("INFORME UM ORGÃO EMISSOR VÁLIDO!");
        }
        if (cbUfRg.getSelectedItem().equals("Selecione...")) {
            cbUfRg.requestFocus();
            throw new Exception("INFORME O UF QUE FOI EMITIDO O RG!");
        }
        if (tfDataEmissaoRg.getText().equals("  /  /    ")) {
            tfDataEmissaoRg.requestFocus();
            throw new Exception("INFORME A DATA DE EMISSÃO DO RG!");

        }

    }

    private void validarData() {

    }

    private void gravar() throws ParseException, Exception {
        ResponsavelLegal responsavel = new ResponsavelLegal();
        Cidade cidade = new Cidade();
        BResponsavel bResponsavel = new BResponsavel();

        cidade.setCidade((String) cbCidade.getSelectedItem());
        cidade.setUf((String) cbUf.getSelectedItem());

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        String dataRg = tfDataEmissaoRg.getText();
        Calendar calRg = Calendar.getInstance();
        calRg.setTime(sdf.parse(dataRg));

        responsavel.setNome(tfNome.getText());
        responsavel.setEndereco(tfEndereco.getText());
        responsavel.setBairro(tfBairro.getText());
        responsavel.setCep(tfCep.getText());
        responsavel.setCidade(cidade);
        responsavel.setTelefone(tfTelefone.getText());
        responsavel.setCelular(tfCelular.getText());
        responsavel.setEmail(tfEmail.getText());
        responsavel.setCpf(tfCpf.getText().replace(".", "").replace("-", ""));
        responsavel.setRg(tfRg.getText());
        responsavel.setOrgaoEmissor(tfOrgaoEmissor.getText());
        responsavel.setUfRg((String) cbUfRg.getSelectedItem());
        responsavel.setEmissaoRg(calRg);

        if (responsavelRecebido.getId() == 0) {
            bResponsavel.gravar(responsavel);
            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
        } else {
            responsavel.setId(responsavelRecebido.getId());
            bResponsavel.alterar(responsavel);
            JOptionPane.showMessageDialog(null, "Alteração realizada com sucesso!");
        }
    }
}
