/*
 * Here comes the text of your license
 * Each line should be prefixed with  * 
 */
package br.com.genises.view.internal;

import br.com.genises.model.Celula;
import br.com.genises.model.Cidade;
import br.com.genises.model.Membro;
import br.com.genises.negocio.BCelula;
import br.com.genises.negocio.BCidade;
import br.com.genises.util.validacoes.UpperCaseDocument;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author rober
 */
public class GUICadastroCelula extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUICadastroCelula
     */
    Membro membroAnfitriao = new Membro();
    Membro lider = new Membro();
    Membro liderTreinamento = new Membro();
    Membro supervisor = new Membro();

    public GUICadastroCelula() {
        initComponents();
        upperCase();
        formatarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        tfNome = new javax.swing.JTextField();
        tfEndereco = new javax.swing.JTextField();
        tfBairro = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfCep = new javax.swing.JTextField();
        cbUf = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        cbCidade = new javax.swing.JComboBox();
        tfAnfitriao = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tfLider = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tfLiderTreinamento = new javax.swing.JTextField();
        tfSupervisor = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tfTelefoneAnfitriao = new javax.swing.JFormattedTextField();
        tfCelularAnfitriao = new javax.swing.JFormattedTextField();
        tfTelefoneLider = new javax.swing.JFormattedTextField();
        tfCelularLider = new javax.swing.JFormattedTextField();
        tfTelefoneLiderTreinamento = new javax.swing.JFormattedTextField();
        tfLiderTreinamentoCelular = new javax.swing.JFormattedTextField();
        tfTelefoneSupervisor = new javax.swing.JFormattedTextField();
        tfCelularSupervisor = new javax.swing.JFormattedTextField();
        tfHorario = new javax.swing.JFormattedTextField();
        cbDia = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("Sistema Gênises - Cadastro de Celulas");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Celula"));

        jLabel1.setText("Nome:");

        jLabel2.setText("Endereço:");

        jLabel3.setText("Bairro:");

        jLabel4.setText("UF:");

        jLabel5.setText("Anfitrião:");

        jLabel6.setText("Telefone:");

        jLabel7.setText("Lider:");

        jLabel8.setText("Telefone:");

        jLabel9.setText("Lider em Treinamento:");

        jLabel10.setText("Telefone:");

        jLabel11.setText("Supervisor:");

        jLabel12.setText("Telefone:");

        jLabel13.setText("Dia da Celula:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/genises/util/imagens/salvar icone_vectorized.png"))); // NOI18N
        jButton1.setText("Gravar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/genises/util/imagens/limpar_vectorized_1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/genises/util/imagens/fechar_vectorized_1.png"))); // NOI18N
        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel14.setText("CEP:");

        cbUf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));
        cbUf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUfActionPerformed(evt);
            }
        });

        jLabel15.setText("Cidade:");

        cbCidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione..." }));

        tfAnfitriao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfAnfitriaoKeyReleased(evt);
            }
        });

        jLabel16.setText("Celular:");

        tfLider.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfLiderKeyReleased(evt);
            }
        });

        jLabel17.setText("Celular:");

        jLabel18.setText("Celular:");

        tfLiderTreinamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfLiderTreinamentoKeyReleased(evt);
            }
        });

        tfSupervisor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfSupervisorKeyReleased(evt);
            }
        });

        jLabel19.setText("Celular:");

        jLabel20.setText("Horario:");

        try {
            tfTelefoneAnfitriao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(0xx##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            tfCelularAnfitriao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(0xx##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            tfTelefoneLider.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(0xx##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            tfCelularLider.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(0xx##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            tfTelefoneLiderTreinamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(0xx##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            tfLiderTreinamentoCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(0xx##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            tfTelefoneSupervisor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(0xx##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            tfCelularSupervisor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(0xx##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            tfHorario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Domingo", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNome)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCep, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                            .addComponent(tfEndereco)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbUf, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbCidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(tfAnfitriao)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfTelefoneAnfitriao, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCelularAnfitriao))
                            .addComponent(tfLider)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfTelefoneLider, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCelularLider))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfTelefoneLiderTreinamento, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfLiderTreinamentoCelular))
                            .addComponent(tfLiderTreinamento)
                            .addComponent(tfSupervisor)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfTelefoneSupervisor, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(cbDia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfHorario))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfCelularSupervisor)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(39, 39, 39))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(tfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(cbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfAnfitriao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel16)
                    .addComponent(tfTelefoneAnfitriao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCelularAnfitriao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfLider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel17)
                    .addComponent(tfTelefoneLider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCelularLider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfLiderTreinamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel18)
                    .addComponent(tfTelefoneLiderTreinamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfLiderTreinamentoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel19)
                    .addComponent(tfTelefoneSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCelularSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel20)
                    .addComponent(tfHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton3)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbUfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUfActionPerformed

        try {
            if (cbUf.getSelectedItem().equals("Selecione...")) {

            } else {
                BCidade bCidade = new BCidade();
                List<Cidade> cidades = new ArrayList<>();
                String uf = (String) cbUf.getSelectedItem();
                cidades = bCidade.buscaCidade(uf);
                cbCidade.setEnabled(true);
                carregarCidades(cidades);
                cbCidade.requestFocus();
            }
        } catch (Exception ex) {

        }            // TODO add your handling code here:
    }//GEN-LAST:event_cbUfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            verificaExistencia();
            verificaCampos();
            gravarDados();
            limparCampos();
// TODO add your handling code here:
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfAnfitriaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfAnfitriaoKeyReleased

        if (tfAnfitriao.getText().equals("")) {

        } else {
            try {
                GUIPesquisaMembros guiPesquisaMembro = new GUIPesquisaMembros(this, "anfitriao", tfAnfitriao.getText());
                tfAnfitriao.setText(null);
                guiPesquisaMembro.setVisible(true);

            } catch (Exception ex) {
                Logger.getLogger(GUICadastroCelula.class.getName()).log(Level.SEVERE, null, ex);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tfAnfitriaoKeyReleased

    private void tfLiderKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfLiderKeyReleased
        if (tfAnfitriao.getText().equals("")) {

        } else {
            try {
                GUIPesquisaMembros guiPesquisaMembro = new GUIPesquisaMembros(this, "lider", tfLider.getText());
                tfLider.setText(null);
                guiPesquisaMembro.setVisible(true);

            } catch (Exception ex) {
                Logger.getLogger(GUICadastroCelula.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_tfLiderKeyReleased

    private void tfLiderTreinamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfLiderTreinamentoKeyReleased
        if (tfAnfitriao.getText().equals("")) {

        } else {
            try {
                GUIPesquisaMembros guiPesquisaMembro = new GUIPesquisaMembros(this, "lider treinamento", tfLiderTreinamento.getText());
                tfLiderTreinamento.setText(null);
                guiPesquisaMembro.setVisible(true);

            } catch (Exception ex) {
                Logger.getLogger(GUICadastroCelula.class.getName()).log(Level.SEVERE, null, ex);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tfLiderTreinamentoKeyReleased

    private void tfSupervisorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSupervisorKeyReleased
        if (tfAnfitriao.getText().equals("")) {

        } else {
            try {
                GUIPesquisaMembros guiPesquisaMembro = new GUIPesquisaMembros(this, "supervisor", tfSupervisor.getText());
                tfSupervisor.setText(null);
                guiPesquisaMembro.setVisible(true);

            } catch (Exception ex) {
                Logger.getLogger(GUICadastroCelula.class.getName()).log(Level.SEVERE, null, ex);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tfSupervisorKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        limparCampos();

// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbCidade;
    private javax.swing.JComboBox<String> cbDia;
    private javax.swing.JComboBox cbUf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfAnfitriao;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JFormattedTextField tfCelularAnfitriao;
    private javax.swing.JFormattedTextField tfCelularLider;
    private javax.swing.JFormattedTextField tfCelularSupervisor;
    private javax.swing.JTextField tfCep;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JFormattedTextField tfHorario;
    private javax.swing.JTextField tfLider;
    private javax.swing.JTextField tfLiderTreinamento;
    private javax.swing.JFormattedTextField tfLiderTreinamentoCelular;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfSupervisor;
    private javax.swing.JFormattedTextField tfTelefoneAnfitriao;
    private javax.swing.JFormattedTextField tfTelefoneLider;
    private javax.swing.JFormattedTextField tfTelefoneLiderTreinamento;
    private javax.swing.JFormattedTextField tfTelefoneSupervisor;
    // End of variables declaration//GEN-END:variables

    private void carregarCidades(List<Cidade> cidades) {
        cbCidade.removeAllItems();
        cbCidade.addItem("Selecione...");
        try {
            for (int i = 0; i < cidades.size(); i++) {

                cbCidade.addItem(cidades.get(i).getCidade());
                cbCidade.setSelectedIndex(0);
            }
        } catch (Exception ex) {
            Logger.getLogger(GUICadastroIgreja.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void verificaCampos() throws Exception {
        if (tfNome.getText().trim().equals("")) {
            tfNome.requestFocus();
            throw new Exception("DIGITE O NOME!");
        }
        if (tfEndereco.getText().trim().equals("")) {
            tfEndereco.requestFocus();
            throw new Exception("DIGITE O ENDEREÇO!");
        }
        if (tfBairro.getText().trim().equals("")) {
            tfBairro.requestFocus();
            throw new Exception("DIGITE O BAIRRO!");
        }
        if (tfCep.getText().trim().equals("")) {
            tfCep.requestFocus();
            throw new Exception("DIGITE O CEP!");
        }
        if (cbUf.getSelectedItem().equals("Selecione...")) {
            cbUf.requestFocus();
            throw new Exception("SELECIONE UM ESTADO!");
        }
        if (cbCidade.getSelectedItem().equals("Selecione...")) {
            cbCidade.requestFocus();
            throw new Exception("SELECIONE UMA CIDADE!");
        }
        if (membroAnfitriao.getId() == 0) {
            tfAnfitriao.requestFocus();
            throw new Exception("INFORME O NOME DO ANFITRIÃO!");
        }
        if (lider.getId() == 0) {
            tfLider.requestFocus();
            throw new Exception("INFORME O NOME DO LIDER!");
        }
        if (liderTreinamento.getId() == 0) {
            tfLiderTreinamento.requestFocus();
            throw new Exception("INFORME O NOME DO LIDER EM TREINAMENTO!");
        }
        if (supervisor.getId() == 0) {
            tfSupervisor.requestFocus();
            throw new Exception("INFORME O NOME DO SUPERVISOR!");
        }
        if (tfHorario.getText().trim().equals(":")) {
            tfHorario.requestFocus();
            throw new Exception("DIGITE O HORÁRIO!");
        }

    }

    private void gravarDados() throws Exception {
        Celula c = new Celula();
        BCelula bCelula = new BCelula();
        Cidade cidade = new Cidade();
        Membro anfitriao = new Membro();

        c.setNome(tfNome.getText());
        c.setEndereco(tfNome.getText());
        c.setBairro(tfBairro.getText());
        c.setCep(tfCep.getText());
        cidade.setUf((String) cbUf.getSelectedItem());
        cidade.setCidade((String) cbCidade.getSelectedItem());
        c.setCidade(cidade);

        c.setAnfitriao(membroAnfitriao);
        c.setLider(lider);
        c.setLiderTreinamemto(liderTreinamento);
        c.setSupervisor(supervisor);

        c.setDia((String) cbDia.getSelectedItem());
        c.setHora(tfHorario.getText());

        bCelula.gravar(c);
        JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso!");

    }

    void setarAnfitriao(Membro membro) {
        tfAnfitriao.setText(membro.getNome());
        tfTelefoneAnfitriao.setText(membro.getTelefone());
        tfCelularAnfitriao.setText(membro.getCelular());
        tfLider.requestFocus();
    }

    void setarLider(Membro membro) {
        tfLider.setText(membro.getNome());
        tfTelefoneLider.setText(membro.getTelefone());
        tfCelularLider.setText(membro.getCelular());
        tfLiderTreinamento.requestFocus();
    }

    void setarLiderTreinamento(Membro membro) {
        tfLiderTreinamento.setText(membro.getNome());
        tfTelefoneLiderTreinamento.setText(membro.getTelefone());
        tfLiderTreinamentoCelular.setText(membro.getCelular());
        tfSupervisor.requestFocus();
    }

    void setarSupervisor(Membro membro) {
        tfSupervisor.setText(membro.getNome());
        tfTelefoneSupervisor.setText(membro.getTelefone());
        tfCelularSupervisor.setText(membro.getCelular());
        cbDia.requestFocus();
    }

    private void upperCase() {
        tfNome.setDocument(new UpperCaseDocument());
        tfBairro.setDocument(new UpperCaseDocument());
        tfEndereco.setDocument(new UpperCaseDocument());
        tfAnfitriao.setDocument(new UpperCaseDocument());
        tfLider.setDocument(new UpperCaseDocument());
        tfLiderTreinamento.setDocument(new UpperCaseDocument());
        tfSupervisor.setDocument(new UpperCaseDocument());

    }

    private void formatarCampos() {
        tfCelularAnfitriao.setEditable(false);
        tfTelefoneAnfitriao.setEditable(false);
        tfCelularLider.setEditable(false);
        tfTelefoneLider.setEditable(false);
        tfCelularSupervisor.setEditable(false);
        tfTelefoneSupervisor.setEditable(false);
        tfLiderTreinamentoCelular.setEditable(false);
        tfTelefoneLiderTreinamento.setEditable(false);

    }

    private void limparCampos() {
        membroAnfitriao = new Membro();
        lider = new Membro();
        liderTreinamento = new Membro();
        supervisor = new Membro();
        tfNome.setText(null);
        tfEndereco.setText(null);
        tfBairro.setText(null);
        tfCep.setText(null);
        tfCelularAnfitriao.setText(null);
        tfTelefoneAnfitriao.setText(null);
        tfAnfitriao.setText(null);
        tfLider.setText(null);
        tfTelefoneLider.setText(null);
        tfCelularLider.setText(null);
        tfLiderTreinamento.setText(null);
        tfTelefoneLiderTreinamento.setText(null);
        tfLiderTreinamentoCelular.setText(null);
        tfSupervisor.setText(null);
        tfTelefoneSupervisor.setText(null);
        tfCelularSupervisor.setText(null);
        tfHorario.setText(null);
        cbUf.setSelectedIndex(0);
        cbCidade.setSelectedIndex(0);
        cbDia.setSelectedIndex(0);

    }

    private void verificaExistencia() throws Exception {

        BCelula bCelulaR = new BCelula();
        Celula celulaV = new Celula(); //celula editada
        celulaV.setNome(tfNome.getText());

        if (bCelulaR.verificaExistencia(celulaV) == true) {
            tfNome.requestFocus();
            throw new Exception("O NOME INFORMADO JÁ EXISTE CADASTRADO!");

        }
    }
}
