/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.genises.view.internal;

import br.com.genises.model.Celula;
import br.com.genises.model.Membro;
import br.com.genises.negocio.BCelula;
import br.com.genises.negocio.BMembro;
import br.com.genises.negocio.ComboMultidata;
import br.com.genises.view.exception.NegocioException;
import br.com.genises.view.util.mensages.JOptionPaneUtil;
import br.com.genises.view.util.tablemodel.CelulasTableModel;
import br.com.genises.view.util.tablemodel.MembroCelulaTableModel;
import br.com.genises.view.util.tablemodel.MembroCelulaTableModel2;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class GUIMultiplicacaoCelulas extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIAdicionarMembrosCelula
     */
    private String campoPesquisa = "";
    private List<String> camposPadrao;
    private String tipoCampo = "";
    private MembroCelulaTableModel tmMembros;
    private MembroCelulaTableModel2 tmMembros2;
    Membro membroSelecionado = new Membro();
    Celula categoria = new Celula();
    Celula celula2 = new Celula();

    public GUIMultiplicacaoCelulas() throws Exception {

        tmMembros = new MembroCelulaTableModel(camposPadrao);
        tmMembros2 = new MembroCelulaTableModel2(camposPadrao);
        initComponents();
        carregarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbCelula = new javax.swing.JComboBox<String>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tMembros = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        cbCelula1 = new javax.swing.JComboBox<String>();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tMembros1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Sistema Gênises - Multiplicar Celulas");

        jLabel1.setText("Celula 1:");

        cbCelula.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione..." }));

        jButton1.setText("Carregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tMembros.setModel(tmMembros);
        jScrollPane1.setViewportView(tMembros);

        jLabel3.setText("Celula 2:");

        cbCelula1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione..." }));

        jButton4.setText("Carregar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tMembros1.setModel(tmMembros2);
        jScrollPane2.setViewportView(tMembros1);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/genises/util/imagens/seta direita .png"))); // NOI18N

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/genises/util/imagens/seta esquerda_vectorized.png"))); // NOI18N

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/genises/util/imagens/limpar_vectorized_1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCelula, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCelula1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbCelula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(cbCelula1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton4)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        carregarTabela();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        carregarTabela2();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbCelula;
    private javax.swing.JComboBox<String> cbCelula1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tMembros;
    private javax.swing.JTable tMembros1;
    // End of variables declaration//GEN-END:variables
    BCelula bCelula = new BCelula();

    private void carregarCombo() throws Exception {
        try {
            List<Celula> celulas = new ArrayList<>();

            celulas = bCelula.listarCelulas();

            DefaultComboBoxModel comboModel = (DefaultComboBoxModel) cbCelula.getModel();
            DefaultComboBoxModel comboModel1 = (DefaultComboBoxModel) cbCelula1.getModel();

            for (int linha = 0; linha < celulas.size(); linha++) {
                //pegando a categoria da lista
                Celula categoria = celulas.get(linha);
                //adicionando a categoria no combo
                comboModel.addElement(categoria);
                comboModel1.addElement(categoria);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Não existem celulas cadastradas!");
            this.dispose();
        }
    }
    List<Membro> membros = new ArrayList<>();
    List<Membro> membros2 = new ArrayList<>();

    private void pesquisarMembros2(long id) throws Exception {

        membros2 = bCelula.pesquisarMembros(id);

        carregarGrid2(membros2);

    }

    private void pesquisarMembros(long id) throws Exception {

        membros = bCelula.pesquisarMembros(id);

        carregarGrid(membros);

    }

    private void carregarGrid2(List<Membro> membros) {
        try {
            tmMembros2.clear();

            if (membros.isEmpty()) {
                JOptionPane.showMessageDialog(this, "A Celula selecionada ainda não possui membros!");
            } else {
                tmMembros2.adicionaList(membros);
            }
        } catch (NegocioException ex) {
            JOptionPaneUtil.messageInformation(ex.getMessage());
        } catch (Exception ex) {
            //   ex.printStackTrace();
//            Celula celula = new Celula();
//            tmCelulas.adiciona(celula);
        }

    }

    private void carregarGrid(List<Membro> membros) {
        try {
            tmMembros.clear();

            if (membros.isEmpty()) {
                JOptionPane.showMessageDialog(this, "A Celula selecionada ainda não possui membros!");
            } else {
                tmMembros.adicionaList(membros);
            }
        } catch (NegocioException ex) {
            JOptionPaneUtil.messageInformation(ex.getMessage());
        } catch (Exception ex) {
            //   ex.printStackTrace();
//            Celula celula = new Celula();
//            tmCelulas.adiciona(celula);
        }

    }

    private void carregarTabela() {
        try {

            if (cbCelula.getSelectedIndex() == 0 && cbCelula1.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Selecione as celulas que deseja multiplicar!");
            } else {
                categoria = (Celula) cbCelula.getSelectedItem();

                if (cbCelula1.getSelectedIndex() == 0) {
                    pesquisarMembros(categoria.getId());
                } else {
                    celula2 = (Celula) cbCelula1.getSelectedItem();
                    if (categoria.getId() == celula2.getId()) {
                        JOptionPane.showMessageDialog(this, "Selecione celulas diferentes!");
                    } else {
                        pesquisarMembros(categoria.getId());
                    }
                }
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Selecione uma celula válida!");
        }

    }

    private void carregarTabela2() {
        try {

            if (cbCelula1.getSelectedIndex() == 0 && cbCelula.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Selecione as celulas que deseja multiplicar!");
            } else {
                celula2 = (Celula) cbCelula1.getSelectedItem();

                if (cbCelula.getSelectedIndex() == 0) {
                    pesquisarMembros2(celula2.getId());
                } else {
                    categoria = (Celula) cbCelula.getSelectedItem();
                    if (celula2.getId() == categoria.getId()) {
                        JOptionPane.showMessageDialog(this, "Selecione celulas diferentes!");
                    } else {
                        pesquisarMembros2(celula2.getId());
                    }
                }
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Selecione uma celula válida!");
        }

    }
}
